import 'package:flutter/material.dart';
import 'header_view/header.dart';
import 'image_view/image.dart';
import 'components/task_list.dart';
import 'components/add_task.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: Color.fromARGB(255, 255, 255, 255),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame1(),
        ]),
      ),
    );
  }
}

class Frame1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Column(
                children: [
                  header(),
                  image(),
                  task_list(),
                ],
              ),
            ],
          ),
        ),
        Container(
            width: 180,
            height: 46,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(0),
              boxShadow: [
                BoxShadow(
                  color: Color.fromARGB(255, 235, 9, 9).withOpacity(0.5),
                  // spreadRadius: 10,
                  // blurRadius: 20,
                  offset: Offset(0, 2),
                ),
              ],
            ),
            child: TextButton(
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (context) => add_task()));
              },
              child: Text("Create task"),
            )),
      ],
    );
  }
}
